Support users operation
pj-pss/app-life-enrichers-community pull request #14
Opened 2018-03-09 07:00 UTC by tsukahara-t

* Supporter/OrganizationUser access to organization cell via Users cell.
* During the operation assistance, the profile and reply are changed to those of the user.
* Make ext cell when support is start.
   * Delete ext cell when support is end.
* when start or end to support, return to top page.

closes #7

2018-03-09 07:49 UTC, dixonsiu requested changes
Please don't write App specific routine in common.js

2018-03-12 02:54 UTC, tsukahara-t commented
Because significant change of to get token process by misunderstanding is necessary.

2018-03-12 04:18 UTC, tsukahara-t commented
* Rename constant.js to app.js
* Move process that switch url (common.js to app.js)
* Profile editing is disabled during operation assistance

2018-03-12 05:12 UTC, dixonsiu approved these changes

2018-03-19 00:29 UTC, atsX approved these changes

2018-03-19 00:30 UTC, merged