Deploy to new app cell
pj-pss/app-life-enrichers-community pull request #4
Opened 2018-03-05 01:59 UTC by tsukahara-t

* deploy to app cell
* fix resource path (url, js, css, json, image)

closes #3

2018-03-05 02:19 UTC, dixonsiu requested changes
1. Please add a default relations.json
1. Please use only one folder (src/html/img or src/html/image) for images

2018-03-05 06:18 UTC, dixonsiu requested changes

2018-03-05 06:18 UTC, dixonsiu commented on launch.json
> +     "web": "https://demo.personium.io/app-life-enrichers-community/__/src/html/index.html",
All development files should be in __/html folder. Please refer to MyBoard.

2018-03-06 00:11 UTC, atsX approved these changes

2018-03-06 00:13 UTC, merged